version: '3.8'

services:
  # Simplified for prototype - using mock services only
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LLM_PROVIDER=mock
      - REDIS_URL=mock
      - DATABASE_URL=mock
    volumes:
      - ./backend:/app
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload

  # Optional: Redis if you want to test with real cache
  # Uncomment below to use real Redis instead of mock
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5